machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

dependencies:
  pre:
    - sudo pip install awsebcli
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn

test:
  override:
    - bash ./scripts/build-circle-ci.sh
    
deployment:
  production:
    branch: master
    commands:
      - bash ./scripts/setup-eb.sh
      - eb deploy
